spring.application.name=BMS_Eve
spring.datasource.url=jdbc:postgresql://localhost:5432/bms_eve
spring.datasource.username=akash
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
